-- ============================================================
-- E4 - Implementacao SQL PostgreSQL
-- Dominio: Plataforma de E-commerce
-- Equipe: BRMW
-- Seções: (1) DDL, (2) DML, (3) Consultas Q1 a Q10
-- ============================================================

-- ============================================================
-- (1) DDL
-- ============================================================

DROP VIEW IF EXISTS vw_resumo_cliente;
DROP TABLE IF EXISTS avaliacao CASCADE;
DROP TABLE IF EXISTS pagamento_boleto CASCADE;
DROP TABLE IF EXISTS pagamento_pix CASCADE;
DROP TABLE IF EXISTS pagamento_cartao CASCADE;
DROP TABLE IF EXISTS pagamento CASCADE;
DROP TABLE IF EXISTS item_pedido CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS logistica CASCADE;
DROP TABLE IF EXISTS cupom CASCADE;
DROP TABLE IF EXISTS estoque CASCADE;
DROP TABLE IF EXISTS produto CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS cliente_telefone CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS cep CASCADE;

CREATE TABLE cep (
    cep VARCHAR(8) PRIMARY KEY,
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf CHAR(2) NOT NULL CHECK (uf ~ '^[A-Z]{2}$')
);

CREATE TABLE cliente (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE CHECK (cpf ~ '^[0-9]{11}$'),
    rua VARCHAR(120) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    complemento VARCHAR(120),
    cep VARCHAR(8) NOT NULL,
    CONSTRAINT fk_cliente_cep FOREIGN KEY (cep) REFERENCES cep(cep)
);

CREATE TABLE cliente_telefone (
    id_cliente INTEGER NOT NULL,
    telefone VARCHAR(20) NOT NULL CHECK (telefone ~ '^[0-9()+ -]{8,20}$'),
    PRIMARY KEY (id_cliente, telefone),
    CONSTRAINT fk_cliente_telefone_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON DELETE CASCADE
);

CREATE TABLE categoria (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT
);

CREATE TABLE produto (
    id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INTEGER NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao TEXT,
    preco NUMERIC(10,2) NOT NULL CHECK (preco > 0),
    preco_comparacao NUMERIC(10,2) CHECK (preco_comparacao IS NULL OR preco_comparacao >= preco),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)
);

CREATE TABLE estoque (
    id_produto INTEGER PRIMARY KEY,
    quantidade INTEGER NOT NULL CHECK (quantidade >= 0),
    estoque_minimo INTEGER NOT NULL CHECK (estoque_minimo >= 0),
    estoque_maximo INTEGER NOT NULL CHECK (estoque_maximo >= estoque_minimo),
    CONSTRAINT ck_estoque_quantidade_maxima CHECK (quantidade <= estoque_maximo),
    CONSTRAINT fk_estoque_produto FOREIGN KEY (id_produto) REFERENCES produto(id_produto) ON DELETE CASCADE
);

CREATE TABLE cupom (
    codigo VARCHAR(30) PRIMARY KEY,
    tipo_desconto VARCHAR(20) NOT NULL CHECK (tipo_desconto IN ('percentual', 'valor')),
    desconto NUMERIC(10,2) NOT NULL CHECK (desconto > 0),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    validade DATE NOT NULL
);

CREATE TABLE logistica (
    id_logistica INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_entrega VARCHAR(30) NOT NULL CHECK (status_entrega IN ('pendente', 'postado', 'em_transito', 'entregue', 'cancelado')),
    codigo_rastreio VARCHAR(40) UNIQUE,
    data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pedido (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL,
    codigo_cupom VARCHAR(30),
    id_logistica INTEGER,
    data_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL CHECK (status IN ('criado', 'pago', 'enviado', 'entregue', 'cancelado')),
    valor_total NUMERIC(10,2) NOT NULL CHECK (valor_total >= 0),
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT fk_pedido_cupom FOREIGN KEY (codigo_cupom) REFERENCES cupom(codigo),
    CONSTRAINT fk_pedido_logistica FOREIGN KEY (id_logistica) REFERENCES logistica(id_logistica)
);

CREATE TABLE item_pedido (
    id_pedido INTEGER NOT NULL,
    id_produto INTEGER NOT NULL,
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    preco_unitario NUMERIC(10,2) NOT NULL CHECK (preco_unitario > 0),
    PRIMARY KEY (id_pedido, id_produto),
    CONSTRAINT fk_item_pedido_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    CONSTRAINT fk_item_pedido_produto FOREIGN KEY (id_produto) REFERENCES produto(id_produto)
);

CREATE TABLE pagamento (
    id_pagamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL UNIQUE,
    tipo_pagamento VARCHAR(20) NOT NULL CHECK (tipo_pagamento IN ('cartao', 'pix', 'boleto')),
    status VARCHAR(30) NOT NULL CHECK (status IN ('pendente', 'aprovado', 'recusado', 'cancelado')),
    valor NUMERIC(10,2) NOT NULL CHECK (valor >= 0),
    data_pagamento TIMESTAMP,
    transacao_gateway VARCHAR(80) UNIQUE,
    CONSTRAINT fk_pagamento_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido)
);

CREATE TABLE pagamento_cartao (
    id_pagamento INTEGER PRIMARY KEY,
    numero_cartao VARCHAR(4) NOT NULL CHECK (numero_cartao ~ '^[0-9]{4}$'),
    nome_titular VARCHAR(120) NOT NULL,
    bandeira_cartao VARCHAR(30) NOT NULL,
    quantidade_parcelas INTEGER NOT NULL CHECK (quantidade_parcelas BETWEEN 1 AND 12),
    CONSTRAINT fk_pagamento_cartao_pagamento FOREIGN KEY (id_pagamento) REFERENCES pagamento(id_pagamento) ON DELETE CASCADE
);

CREATE TABLE pagamento_pix (
    id_pagamento INTEGER PRIMARY KEY,
    chave_pix VARCHAR(120) NOT NULL,
    data_expiracao TIMESTAMP NOT NULL,
    CONSTRAINT fk_pagamento_pix_pagamento FOREIGN KEY (id_pagamento) REFERENCES pagamento(id_pagamento) ON DELETE CASCADE
);

CREATE TABLE pagamento_boleto (
    id_pagamento INTEGER PRIMARY KEY,
    codigo_barras VARCHAR(80) NOT NULL UNIQUE,
    data_vencimento DATE NOT NULL,
    CONSTRAINT fk_pagamento_boleto_pagamento FOREIGN KEY (id_pagamento) REFERENCES pagamento(id_pagamento) ON DELETE CASCADE
);

CREATE TABLE avaliacao (
    id_avaliacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL,
    id_produto INTEGER NOT NULL,
    nota INTEGER NOT NULL CHECK (nota BETWEEN 1 AND 5),
    comentario TEXT,
    data_avaliacao DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT fk_avaliacao_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT fk_avaliacao_produto FOREIGN KEY (id_produto) REFERENCES produto(id_produto),
    CONSTRAINT uq_avaliacao_cliente_produto UNIQUE (id_cliente, id_produto)
);

COMMENT ON TABLE cep IS 'Tabela de CEPs normalizada para evitar repeticao de bairro, cidade e UF em cliente.';
COMMENT ON COLUMN cep.cep IS 'Codigo postal usado como chave primaria.';
COMMENT ON COLUMN cep.bairro IS 'Bairro associado ao CEP.';
COMMENT ON COLUMN cep.cidade IS 'Cidade associada ao CEP.';
COMMENT ON COLUMN cep.uf IS 'Unidade federativa com duas letras.';

COMMENT ON TABLE cliente IS 'Clientes cadastrados na plataforma de e-commerce.';
COMMENT ON COLUMN cliente.id_cliente IS 'Identificador unico do cliente.';
COMMENT ON COLUMN cliente.nome IS 'Nome completo do cliente.';
COMMENT ON COLUMN cliente.email IS 'E-mail unico usado para contato e login.';
COMMENT ON COLUMN cliente.senha IS 'Senha armazenada pela aplicacao.';
COMMENT ON COLUMN cliente.cpf IS 'CPF unico do cliente, com onze digitos.';
COMMENT ON COLUMN cliente.rua IS 'Rua do endereco principal.';
COMMENT ON COLUMN cliente.numero IS 'Numero do endereco principal.';
COMMENT ON COLUMN cliente.complemento IS 'Complemento opcional do endereco.';
COMMENT ON COLUMN cliente.cep IS 'CEP do endereco principal, referenciando a tabela cep.';

COMMENT ON TABLE cliente_telefone IS 'Telefones dos clientes, derivados do atributo multivalorado telefone.';
COMMENT ON COLUMN cliente_telefone.id_cliente IS 'Cliente dono do telefone.';
COMMENT ON COLUMN cliente_telefone.telefone IS 'Numero de telefone do cliente.';

COMMENT ON TABLE categoria IS 'Categorias usadas para organizar produtos.';
COMMENT ON COLUMN categoria.id_categoria IS 'Identificador unico da categoria.';
COMMENT ON COLUMN categoria.nome IS 'Nome unico da categoria.';
COMMENT ON COLUMN categoria.descricao IS 'Descricao textual da categoria.';

COMMENT ON TABLE produto IS 'Produtos comercializados na plataforma.';
COMMENT ON COLUMN produto.id_produto IS 'Identificador unico do produto.';
COMMENT ON COLUMN produto.id_categoria IS 'Categoria a que o produto pertence.';
COMMENT ON COLUMN produto.nome IS 'Nome comercial do produto.';
COMMENT ON COLUMN produto.descricao IS 'Descricao detalhada do produto.';
COMMENT ON COLUMN produto.preco IS 'Preco atual de venda.';
COMMENT ON COLUMN produto.preco_comparacao IS 'Preco de referencia para comparacao promocional.';
COMMENT ON COLUMN produto.ativo IS 'Indica se o produto esta disponivel para venda.';

COMMENT ON TABLE estoque IS 'Controle de estoque por produto.';
COMMENT ON COLUMN estoque.id_produto IS 'Produto controlado pelo estoque; tambem e chave primaria.';
COMMENT ON COLUMN estoque.quantidade IS 'Quantidade disponivel em estoque.';
COMMENT ON COLUMN estoque.estoque_minimo IS 'Quantidade minima desejada.';
COMMENT ON COLUMN estoque.estoque_maximo IS 'Quantidade maxima suportada.';

COMMENT ON TABLE cupom IS 'Cupons promocionais aplicaveis aos pedidos.';
COMMENT ON COLUMN cupom.codigo IS 'Codigo do cupom informado no pedido.';
COMMENT ON COLUMN cupom.tipo_desconto IS 'Tipo de desconto: percentual ou valor.';
COMMENT ON COLUMN cupom.desconto IS 'Valor numerico do desconto.';
COMMENT ON COLUMN cupom.ativo IS 'Indica se o cupom pode ser usado.';
COMMENT ON COLUMN cupom.validade IS 'Data limite de validade do cupom.';

COMMENT ON TABLE logistica IS 'Informacoes de rastreamento e status de entrega.';
COMMENT ON COLUMN logistica.id_logistica IS 'Identificador unico do registro logistico.';
COMMENT ON COLUMN logistica.status_entrega IS 'Situacao atual da entrega.';
COMMENT ON COLUMN logistica.codigo_rastreio IS 'Codigo de rastreamento informado pela transportadora.';
COMMENT ON COLUMN logistica.data_atualizacao IS 'Data e hora da ultima atualizacao logistica.';

COMMENT ON TABLE pedido IS 'Pedidos realizados pelos clientes.';
COMMENT ON COLUMN pedido.id_pedido IS 'Identificador unico do pedido.';
COMMENT ON COLUMN pedido.id_cliente IS 'Cliente que realizou o pedido.';
COMMENT ON COLUMN pedido.codigo_cupom IS 'Cupom opcional aplicado ao pedido.';
COMMENT ON COLUMN pedido.id_logistica IS 'Registro logistico opcional do pedido.';
COMMENT ON COLUMN pedido.data_pedido IS 'Data e hora de criacao do pedido.';
COMMENT ON COLUMN pedido.status IS 'Status comercial do pedido.';
COMMENT ON COLUMN pedido.valor_total IS 'Valor total do pedido apos itens e descontos.';

COMMENT ON TABLE item_pedido IS 'Tabela associativa entre pedido e produto.';
COMMENT ON COLUMN item_pedido.id_pedido IS 'Pedido que contem o item.';
COMMENT ON COLUMN item_pedido.id_produto IS 'Produto comprado no pedido.';
COMMENT ON COLUMN item_pedido.quantidade IS 'Quantidade comprada do produto.';
COMMENT ON COLUMN item_pedido.preco_unitario IS 'Preco praticado no momento da compra.';

COMMENT ON TABLE pagamento IS 'Pagamento associado a um pedido.';
COMMENT ON COLUMN pagamento.id_pagamento IS 'Identificador unico do pagamento.';
COMMENT ON COLUMN pagamento.id_pedido IS 'Pedido pago.';
COMMENT ON COLUMN pagamento.tipo_pagamento IS 'Metodo usado no pagamento.';
COMMENT ON COLUMN pagamento.status IS 'Situacao do pagamento.';
COMMENT ON COLUMN pagamento.valor IS 'Valor pago.';
COMMENT ON COLUMN pagamento.data_pagamento IS 'Data e hora de processamento do pagamento.';
COMMENT ON COLUMN pagamento.transacao_gateway IS 'Codigo unico da transacao no gateway.';

COMMENT ON TABLE pagamento_cartao IS 'Atributos especificos de pagamento por cartao.';
COMMENT ON COLUMN pagamento_cartao.id_pagamento IS 'Pagamento especializado como cartao.';
COMMENT ON COLUMN pagamento_cartao.numero_cartao IS 'Ultimos quatro digitos do cartao.';
COMMENT ON COLUMN pagamento_cartao.nome_titular IS 'Nome impresso no cartao.';
COMMENT ON COLUMN pagamento_cartao.bandeira_cartao IS 'Bandeira do cartao.';
COMMENT ON COLUMN pagamento_cartao.quantidade_parcelas IS 'Quantidade de parcelas escolhida.';

COMMENT ON TABLE pagamento_pix IS 'Atributos especificos de pagamento por Pix.';
COMMENT ON COLUMN pagamento_pix.id_pagamento IS 'Pagamento especializado como Pix.';
COMMENT ON COLUMN pagamento_pix.chave_pix IS 'Chave Pix ou identificador de cobranca.';
COMMENT ON COLUMN pagamento_pix.data_expiracao IS 'Data e hora de expiracao da cobranca Pix.';

COMMENT ON TABLE pagamento_boleto IS 'Atributos especificos de pagamento por boleto.';
COMMENT ON COLUMN pagamento_boleto.id_pagamento IS 'Pagamento especializado como boleto.';
COMMENT ON COLUMN pagamento_boleto.codigo_barras IS 'Codigo de barras do boleto.';
COMMENT ON COLUMN pagamento_boleto.data_vencimento IS 'Data de vencimento do boleto.';

COMMENT ON TABLE avaliacao IS 'Avaliacoes feitas por clientes sobre produtos.';
COMMENT ON COLUMN avaliacao.id_avaliacao IS 'Identificador unico da avaliacao.';
COMMENT ON COLUMN avaliacao.id_cliente IS 'Cliente que fez a avaliacao.';
COMMENT ON COLUMN avaliacao.id_produto IS 'Produto avaliado.';
COMMENT ON COLUMN avaliacao.nota IS 'Nota de 1 a 5 atribuida ao produto.';
COMMENT ON COLUMN avaliacao.comentario IS 'Comentario textual opcional.';
COMMENT ON COLUMN avaliacao.data_avaliacao IS 'Data em que a avaliacao foi registrada.';

-- ============================================================
-- (2) DML - Dados de teste
-- ============================================================

INSERT INTO cep (cep, bairro, cidade, uf) VALUES
('30140071', 'Savassi', 'Belo Horizonte', 'MG'),
('30130110', 'Funcionarios', 'Belo Horizonte', 'MG'),
('30310400', 'Serra', 'Belo Horizonte', 'MG'),
('30431010', 'Buritis', 'Belo Horizonte', 'MG'),
('30575180', 'Barreiro', 'Belo Horizonte', 'MG'),
('30640070', 'Eldorado', 'Contagem', 'MG'),
('31710000', 'Pampulha', 'Belo Horizonte', 'MG'),
('34006056', 'Vila da Serra', 'Nova Lima', 'MG'),
('36010071', 'Centro', 'Juiz de Fora', 'MG'),
('38400100', 'Centro', 'Uberlandia', 'MG');

INSERT INTO cliente (id_cliente, nome, email, senha, cpf, rua, numero, complemento, cep) VALUES
(1, 'Ana Beatriz Martins', 'ana.martins@example.com', 'hash_ana', '11122233344', 'Rua Pernambuco', '1200', 'Apto 401', '30130110'),
(2, 'Bruno Carvalho Lima', 'bruno.lima@example.com', 'hash_bruno', '22233344455', 'Avenida Afonso Pena', '2200', NULL, '30140071'),
(3, 'Carla Mendes Rocha', 'carla.rocha@example.com', 'hash_carla', '33344455566', 'Rua do Ouro', '315', 'Casa', '30310400'),
(4, 'Diego Santos Reis', 'diego.reis@example.com', 'hash_diego', '44455566677', 'Avenida Professor Mario Werneck', '1801', 'Bloco B', '30431010'),
(5, 'Elisa Fernanda Alves', 'elisa.alves@example.com', 'hash_elisa', '55566677788', 'Rua Visconde de Ibituruna', '44', NULL, '30575180'),
(6, 'Felipe Gomes Pereira', 'felipe.pereira@example.com', 'hash_felipe', '66677788899', 'Avenida Joao Cesar de Oliveira', '900', 'Sala 12', '30640070'),
(7, 'Gabriela Nunes Vieira', 'gabriela.vieira@example.com', 'hash_gabriela', '77788899900', 'Avenida Antonio Carlos', '6627', NULL, '31710000'),
(8, 'Henrique Costa Duarte', 'henrique.duarte@example.com', 'hash_henrique', '88899900011', 'Alameda Oscar Niemeyer', '500', 'Apto 1202', '34006056'),
(9, 'Isabela Teixeira Moura', 'isabela.moura@example.com', 'hash_isabela', '99900011122', 'Rua Halfeld', '82', NULL, '36010071'),
(10, 'Joao Pedro Faria', 'joao.faria@example.com', 'hash_joao', '00011122233', 'Avenida Floriano Peixoto', '1450', 'Apto 703', '38400100');

INSERT INTO cliente_telefone (id_cliente, telefone) VALUES
(1, '(31) 98888-1001'),
(1, '(31) 97777-1001'),
(2, '(31) 98888-1002'),
(3, '(31) 98888-1003'),
(4, '(31) 98888-1004'),
(5, '(31) 98888-1005'),
(6, '(31) 98888-1006'),
(7, '(31) 98888-1007'),
(8, '(31) 98888-1008'),
(9, '(32) 98888-1009'),
(10, '(34) 98888-1010'),
(10, '(34) 97777-1010');

INSERT INTO categoria (id_categoria, nome, descricao) VALUES
(1, 'Smartphones', 'Celulares e acessorios moveis'),
(2, 'Informatica', 'Computadores, notebooks e componentes'),
(3, 'Games', 'Consoles, jogos e acessorios gamer'),
(4, 'Audio', 'Fones, caixas de som e equipamentos de audio'),
(5, 'Casa Inteligente', 'Dispositivos conectados para automacao residencial'),
(6, 'Eletroportateis', 'Equipamentos compactos para cozinha e casa'),
(7, 'Livros', 'Livros fisicos e digitais'),
(8, 'Escritorio', 'Produtos para produtividade e escritorio'),
(9, 'Fotografia', 'Cameras e acessorios fotograficos'),
(10, 'Wearables', 'Relogios e pulseiras inteligentes');

INSERT INTO produto (id_produto, id_categoria, nome, descricao, preco, preco_comparacao, ativo) VALUES
(1, 1, 'Smartphone Orion 128GB', 'Smartphone 5G com tela AMOLED e 128GB de armazenamento.', 2499.90, 2799.90, TRUE),
(2, 2, 'Notebook Atlas 14', 'Notebook ultrafino com 16GB de RAM e SSD de 512GB.', 4599.00, 4999.00, TRUE),
(3, 3, 'Controle Pro Wireless', 'Controle sem fio compativel com consoles e PC.', 349.90, 399.90, TRUE),
(4, 4, 'Fone Wave ANC', 'Fone Bluetooth com cancelamento ativo de ruido.', 599.90, 699.90, TRUE),
(5, 5, 'Lampada Smart RGB', 'Lampada inteligente RGB com controle por aplicativo.', 89.90, 119.90, TRUE),
(6, 6, 'Air Fryer Compact 4L', 'Fritadeira eletrica sem oleo com cesto de 4 litros.', 429.90, 499.90, TRUE),
(7, 7, 'Livro SQL na Pratica', 'Livro introdutorio sobre modelagem e consultas SQL.', 79.90, 99.90, TRUE),
(8, 8, 'Cadeira Ergonomica Flex', 'Cadeira de escritorio com ajuste lombar.', 899.90, 1099.90, TRUE),
(9, 9, 'Camera Action 4K', 'Camera compacta para esportes com gravacao 4K.', 1199.90, 1399.90, TRUE),
(10, 10, 'Smartwatch Pulse', 'Relogio inteligente com monitoramento de saude.', 749.90, 849.90, TRUE);

INSERT INTO estoque (id_produto, quantidade, estoque_minimo, estoque_maximo) VALUES
(1, 18, 5, 80),
(2, 7, 3, 40),
(3, 42, 10, 100),
(4, 20, 6, 80),
(5, 85, 20, 200),
(6, 12, 4, 50),
(7, 60, 15, 150),
(8, 5, 3, 30),
(9, 4, 5, 25),
(10, 9, 6, 60);

INSERT INTO cupom (codigo, tipo_desconto, desconto, ativo, validade) VALUES
('BEMVINDO10', 'percentual', 10.00, TRUE, '2026-12-31'),
('FRETE20', 'valor', 20.00, TRUE, '2026-08-31'),
('TECH15', 'percentual', 15.00, TRUE, '2026-07-15'),
('GAMES25', 'valor', 25.00, TRUE, '2026-09-30'),
('AUDIO12', 'percentual', 12.00, TRUE, '2026-10-31'),
('CASA30', 'valor', 30.00, TRUE, '2026-11-30'),
('LIVROS5', 'percentual', 5.00, TRUE, '2026-12-20'),
('OFFICE50', 'valor', 50.00, TRUE, '2026-12-15'),
('FOTO8', 'percentual', 8.00, FALSE, '2026-05-31'),
('PULSE10', 'percentual', 10.00, TRUE, '2026-09-10');

INSERT INTO logistica (id_logistica, status_entrega, codigo_rastreio, data_atualizacao) VALUES
(1, 'entregue', 'BRMW000001MG', '2026-05-02 14:20:00'),
(2, 'em_transito', 'BRMW000002MG', '2026-05-04 09:10:00'),
(3, 'postado', 'BRMW000003MG', '2026-05-05 16:45:00'),
(4, 'entregue', 'BRMW000004MG', '2026-05-07 18:30:00'),
(5, 'pendente', 'BRMW000005MG', '2026-05-09 08:00:00'),
(6, 'em_transito', 'BRMW000006MG', '2026-05-10 11:50:00'),
(7, 'entregue', 'BRMW000007MG', '2026-05-12 17:40:00'),
(8, 'cancelado', 'BRMW000008MG', '2026-05-13 10:15:00'),
(9, 'postado', 'BRMW000009MG', '2026-05-15 13:25:00'),
(10, 'pendente', 'BRMW000010MG', '2026-05-16 09:05:00');

INSERT INTO pedido (id_pedido, id_cliente, codigo_cupom, id_logistica, data_pedido, status, valor_total) VALUES
(1, 1, 'BEMVINDO10', 1, '2026-05-01 10:15:00', 'entregue', 2564.82),
(2, 2, NULL, 2, '2026-05-03 11:20:00', 'enviado', 5198.90),
(3, 3, 'GAMES25', 3, '2026-05-04 12:05:00', 'pago', 504.70),
(4, 4, 'AUDIO12', 4, '2026-05-06 16:45:00', 'entregue', 598.22),
(5, 5, 'CASA30', 5, '2026-05-08 09:30:00', 'pago', 319.60),
(6, 6, NULL, 6, '2026-05-09 14:10:00', 'enviado', 519.80),
(7, 7, 'LIVROS5', 7, '2026-05-11 19:25:00', 'entregue', 237.22),
(8, 8, 'OFFICE50', 8, '2026-05-12 08:50:00', 'cancelado', 929.80),
(9, 9, NULL, 9, '2026-05-14 15:00:00', 'pago', 1799.80),
(10, 10, 'PULSE10', 10, '2026-05-15 20:35:00', 'criado', 836.73);

INSERT INTO item_pedido (id_pedido, id_produto, quantidade, preco_unitario) VALUES
(1, 1, 1, 2499.90),
(1, 3, 1, 349.90),
(2, 2, 1, 4599.00),
(3, 3, 1, 349.90),
(4, 4, 1, 599.90),
(5, 5, 3, 89.90),
(6, 6, 1, 429.90),
(7, 7, 2, 79.90),
(8, 8, 1, 899.90),
(9, 9, 1, 1199.90),
(10, 10, 1, 749.90),
(2, 4, 1, 599.90),
(3, 5, 2, 89.90),
(4, 7, 1, 79.90),
(5, 7, 1, 79.90),
(6, 5, 1, 89.90),
(7, 5, 1, 89.90),
(8, 7, 1, 79.90),
(9, 4, 1, 599.90),
(10, 5, 2, 89.90);

INSERT INTO pagamento (id_pagamento, id_pedido, tipo_pagamento, status, valor, data_pagamento, transacao_gateway) VALUES
(1, 1, 'cartao', 'aprovado', 2564.82, '2026-05-01 10:16:00', 'GTW-0001'),
(2, 2, 'cartao', 'aprovado', 5198.90, '2026-05-03 11:21:00', 'GTW-0002'),
(3, 3, 'pix', 'aprovado', 504.70, '2026-05-04 12:06:00', 'GTW-0003'),
(4, 4, 'boleto', 'aprovado', 598.22, '2026-05-06 16:47:00', 'GTW-0004'),
(5, 5, 'pix', 'aprovado', 319.60, '2026-05-08 09:31:00', 'GTW-0005'),
(6, 6, 'boleto', 'aprovado', 519.80, '2026-05-09 14:11:00', 'GTW-0006'),
(7, 7, 'cartao', 'aprovado', 237.22, '2026-05-11 19:26:00', 'GTW-0007'),
(8, 8, 'pix', 'cancelado', 929.80, '2026-05-12 08:51:00', 'GTW-0008'),
(9, 9, 'boleto', 'pendente', 1799.80, NULL, 'GTW-0009'),
(10, 10, 'cartao', 'pendente', 836.73, NULL, 'GTW-0010');

INSERT INTO pagamento_cartao (id_pagamento, numero_cartao, nome_titular, bandeira_cartao, quantidade_parcelas) VALUES
(1, '1234', 'Ana Beatriz Martins', 'Visa', 6),
(2, '5678', 'Bruno Carvalho Lima', 'Mastercard', 10),
(7, '9012', 'Gabriela Nunes Vieira', 'Elo', 1),
(10, '3456', 'Joao Pedro Faria', 'Visa', 3);

INSERT INTO pagamento_pix (id_pagamento, chave_pix, data_expiracao) VALUES
(3, 'pix-gtw-0003', '2026-05-04 12:35:00'),
(5, 'pix-gtw-0005', '2026-05-08 10:00:00'),
(8, 'pix-gtw-0008', '2026-05-12 09:20:00');

INSERT INTO pagamento_boleto (id_pagamento, codigo_barras, data_vencimento) VALUES
(4, '23793381286000000001234000000001234567890123', '2026-05-09'),
(6, '34191790010104351004791020150008291070026000', '2026-05-12'),
(9, '10499876543210000000011999000000000000000009', '2026-05-20');

INSERT INTO avaliacao (id_avaliacao, id_cliente, id_produto, nota, comentario, data_avaliacao) VALUES
(1, 1, 1, 5, 'Produto rapido e com boa camera.', '2026-05-05'),
(2, 2, 2, 4, 'Notebook muito bom para trabalho.', '2026-05-06'),
(3, 3, 3, 5, 'Controle confortavel e responsivo.', '2026-05-07'),
(4, 4, 4, 4, 'Cancelamento de ruido eficiente.', '2026-05-09'),
(5, 5, 5, 5, 'Facil de configurar no aplicativo.', '2026-05-10'),
(6, 6, 6, 4, 'Atende bem uma familia pequena.', '2026-05-12'),
(7, 7, 7, 5, 'Conteudo claro para estudar SQL.', '2026-05-13'),
(8, 8, 8, 3, 'Boa cadeira, mas montagem demorada.', '2026-05-14'),
(9, 1, 3, 4, 'Bom acessorio para jogos no PC.', '2026-05-15'),
(10, 2, 4, 5, 'Audio excelente em chamadas.', '2026-05-16');

-- ============================================================
-- (3) Consultas Q1 a Q10
-- ============================================================

-- Q1 - Quais produtos ativos de tecnologia custam entre R$ 300 e R$ 5.000?
SELECT id_produto, nome, preco
FROM produto
WHERE ativo = TRUE
  AND preco BETWEEN 300 AND 5000
  AND id_categoria IN (1, 2, 3, 4, 10)
ORDER BY preco DESC;

-- Q2 - Quais clientes de Belo Horizonte possuem e-mail do dominio example.com e nome iniciado por A, B ou C?
SELECT c.id_cliente, c.nome, c.email, cep.cidade
FROM cliente c
INNER JOIN cep ON cep.cep = c.cep
WHERE cep.cidade = 'Belo Horizonte'
  AND c.email LIKE '%@example.com'
  AND (c.nome LIKE 'A%' OR c.nome LIKE 'B%' OR c.nome LIKE 'C%')
ORDER BY c.nome;

-- Q3 - Quais pedidos foram feitos por cada cliente?
SELECT p.id_pedido, c.nome AS cliente, p.status, p.valor_total, p.data_pedido
FROM pedido p
INNER JOIN cliente c ON c.id_cliente = p.id_cliente
ORDER BY p.data_pedido;

-- Q4 - Quais produtos aparecem em cada pedido, com sua categoria e subtotal do item?
SELECT
    p.id_pedido,
    pr.nome AS produto,
    ca.nome AS categoria,
    ip.quantidade,
    ip.preco_unitario,
    ip.quantidade * ip.preco_unitario AS subtotal_item
FROM item_pedido ip
INNER JOIN pedido p ON p.id_pedido = ip.id_pedido
INNER JOIN produto pr ON pr.id_produto = ip.id_produto
INNER JOIN categoria ca ON ca.id_categoria = pr.id_categoria
ORDER BY p.id_pedido, pr.nome;

-- Q5 - Quais produtos ainda nao possuem avaliacao?
SELECT pr.id_produto, pr.nome, av.id_avaliacao
FROM produto pr
LEFT OUTER JOIN avaliacao av ON av.id_produto = pr.id_produto
WHERE av.id_avaliacao IS NULL
ORDER BY pr.nome;

-- Q6 - Quais categorias venderam mais de R$ 500 em pedidos nao cancelados?
SELECT
    ca.nome AS categoria,
    COUNT(DISTINCT p.id_pedido) AS total_pedidos,
    SUM(ip.quantidade * ip.preco_unitario) AS receita_bruta
FROM categoria ca
INNER JOIN produto pr ON pr.id_categoria = ca.id_categoria
INNER JOIN item_pedido ip ON ip.id_produto = pr.id_produto
INNER JOIN pedido p ON p.id_pedido = ip.id_pedido
WHERE p.status <> 'cancelado'
GROUP BY ca.nome
HAVING SUM(ip.quantidade * ip.preco_unitario) > 500
ORDER BY receita_bruta DESC;

-- Q7 - Quais produtos custam acima da media de preco do catalogo?
SELECT id_produto, nome, preco
FROM produto
WHERE preco > (
    SELECT AVG(preco)
    FROM produto
)
ORDER BY preco DESC;

-- Q8 - Quais clientes possuem pedido acima da media dos pedidos dos demais clientes?
SELECT c.id_cliente, c.nome
FROM cliente c
WHERE EXISTS (
    SELECT 1
    FROM pedido p
    WHERE p.id_cliente = c.id_cliente
      AND p.status <> 'cancelado'
      AND p.valor_total > (
          SELECT AVG(p2.valor_total)
          FROM pedido p2
          WHERE p2.id_cliente <> c.id_cliente
            AND p2.status <> 'cancelado'
      )
)
ORDER BY c.nome;

-- Q9 - Visao de resumo: quanto cada cliente comprou e quantos pedidos possui?
CREATE OR REPLACE VIEW vw_resumo_cliente AS
SELECT
    c.id_cliente,
    c.nome,
    COUNT(p.id_pedido) AS quantidade_pedidos,
    COALESCE(SUM(p.valor_total), 0) AS valor_total_comprado
FROM cliente c
LEFT JOIN pedido p ON p.id_cliente = c.id_cliente
GROUP BY c.id_cliente, c.nome;

SELECT *
FROM vw_resumo_cliente
ORDER BY valor_total_comprado DESC, nome;

-- Q10 - Pergunta de negocio: quais produtos devem ser priorizados para reposicao por terem estoque baixo e historico de venda?
SELECT
    pr.id_produto,
    pr.nome,
    es.quantidade,
    es.estoque_minimo,
    COALESCE(SUM(CASE WHEN p.id_pedido IS NOT NULL THEN ip.quantidade ELSE 0 END), 0) AS unidades_vendidas,
    COALESCE(SUM(CASE WHEN p.id_pedido IS NOT NULL THEN ip.quantidade * ip.preco_unitario ELSE 0 END), 0) AS receita_gerada
FROM produto pr
INNER JOIN estoque es ON es.id_produto = pr.id_produto
LEFT JOIN item_pedido ip ON ip.id_produto = pr.id_produto
LEFT JOIN pedido p ON p.id_pedido = ip.id_pedido AND p.status <> 'cancelado'
WHERE es.quantidade <= es.estoque_minimo
GROUP BY pr.id_produto, pr.nome, es.quantidade, es.estoque_minimo
ORDER BY receita_gerada DESC, unidades_vendidas DESC;
